print(f"1: true and true: {True & True}")
print(f"2: True and false: {True & False}")
print(f"3: 1==1 and 2==1: {1==1 & 2==1}")
print(f"4: 'test' == 'test': {'test'=='test'}")
print(f"5: 1 == 1 | 2 != 1: {1 == 1 | 2 != 1}")
print(f"6: True and 1==1: {True & 1 == 1}")
print(f"7: False and 0 != 0: {False & 0 != 0}")
print(f"8: True or 1 == 1: {True & 1 == 1}")
print(f"9: 'test' == 'testing': {'test' == 'testing'}")
print(f"10: 1 != 0 & 2 == 1: {1 != 0 & 2 == 1}")
print(f"11: 'test' != 'testing': {'test' != 'testing'}")
print(f"12: 'Test' == 1: {'test' == 1}")
print(f"13: not (true and false): {not(True & False)}")
print(f"14: not (1==1 and 0 !=1): {not (1==1 and 0 !=1)}")
print(f"15: not(10 == 1 or 1000 == 1000): {not(10 == 1 | 1000 == 1000)}")
print(f"16: not(1 != 10 or 3 == 4): {not(1 != 10 or 3 == 4)}")
print(f"17: not('testing' == 'testing' and 'zed' == 'cool guy'): {not('testing' == 'testing' and 'zed' == 'cool guy')}")
print(f"18: 1 == 1 and (not ('testing' == 1 or 1 == 0)): {1 == 1 and (not ('testing' == 1 or 1 == 0))}")
print(f"19: 'chunky' == 'bacon' and (not (3 == 4 or 3 == 3)): {'chunky' == 'bacon' and (not (3 == 4 or 3 == 3))}")
print(f"20: 3 == 3 and (not ('testing' == 'testing' or 'python' == 'fun')): {3 == 3 and (not ('testing' == 'testing' or 'python' == 'fun'))}")